### ISSUE TITLE
Enable image tag update in manifests when releasing

### ISSUE THREAD

**Issue by tumido** [open-services-group/peribolos-as-a-service#33]
@harshad16  please provide details on this feature of AiCoE-CI and how to integrate it with release process.

I assume defining the `deploy` section makes some of it happen? 
https://github.com/AICoE/aicoe-ci/blob/13370a07d8005973416ff600f75de12ed45b3000/docs/.aicoe-ci.yaml#L18

**Comment by harshad16** [comment]
This contain the required content: https://github.com/AICoE/aicoe-ci/blob/13370a07d8005973416ff600f75de12ed45b3000/docs/.aicoe-ci.yaml#L18
As you linked.

some extra details:
1. Requires Sesheta to have access to this repo.
Already done: https://github.com/open-services-group/community/blob/2a2526b9a78d3cb00d918d70ed09f784e0dc9388/github-config.yaml#L8
2.  As of now aicoe-ci can only update imagestream and jobs on desired manifest.
If we would like to extend for deploymentconfig, open a request in aicoe-ci.
or else leverage the current behaviour, by setting up imagestream in [manifests](https://github.com/open-services-group/peribolos-as-a-service/tree/main/manifests)
change the deployment to use imagestream instead of direct [image](https://github.com/open-services-group/peribolos-as-a-service/blob/c432c52aea3a901e7bf82db499a62dc39b919505/manifests/deployment-config.yaml#L23)
