### ISSUE TITLE
Handle org config dump if not present

### ISSUE THREAD

**Issue by tumido** [open-services-group/peribolos-as-a-service#9]
Depends on: https://github.com/open-services-group/peribolos-as-a-service/issues/6

Execute peribolos to dump config and open it as a PR.

Create a tekton task: 
2. Git clones the `.github` repo
3. Runs peribolos dump config
4. Git push and open PR

Update app install handler from https://github.com/open-services-group/peribolos-as-a-service/issues/6 to
1. Create `.github` repository if not present
2. And execute the tekton task defined above

**Comment by SamoKopecky** [comment]
I stumbled upon an issue when testing the `config-dump` task together with the controller. When the controller receives app install webhook and creates a `taskrun` for the `config-dump` task with the newly created token, peribolos fails with the following:
```
"error":"failed to obtain username for this token"
```
I tracked this down to [this](https://github.com/kubernetes/test-infra/blob/57d87e2f4085e5b549585cb918c5783400a0b8c3/prow/github/client.go#L1304-L1312) function in the peribolos source code which is called [here](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/main.go#L245) in the peribolos binary. It tries to get the username to check if the user that owns the token is the admin of the org ([here](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/main.go#L257-L259)). 
I tried to manually call the api endpoint to see the reason it fails. So from this call
```bash
curl -H "Accept: application/vnd.github.v3+json" \
 -H "Authorization: Bearer <installation token taken from the created secret>"  \
https://api.github.com/user
```
I got this response:
```json
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/users#get-the-authenticated-user"
}
```
I assume this is because the token is created for an app and a github app is not a user, so peribolos can't get its name and just fails.
I check the peribolos `--help` output to see if there maybe is an option to use with an app, but there doesn't seem to be one. I am going to try to look for some solution, but right now I don't have anything and wanted to put this out there so that maybe someone else knows a solution to this problem.
